version: "3.8"

services:
  postgresql:
    image: postgres:14-alpine
    container_name: libraria-psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ak200222
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  init-db:
    image: postgres:14-alpine
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
      - ./libraria.sql:/docker-entrypoint-initdb.d/libraria.sql
    command:
      - ./docker-entrypoint-initdb.d/init_db.sh
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ak200222
      - HOST=libraria-psql
  app:
    image: libraria
    container_name: libraria-app
    ports:
      - "80:8000"
    depends_on:
      - init-db